# Generated by Django 3.2.9 on 2022-03-01 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KidTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ImageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(max_length=100, null=True)),
                ('Food_group', models.CharField(choices=[('veg', 'Veg'), ('fruit', 'Fruit'), ('grain', 'Grain'), ('protein', 'Protein'), ('dairy', 'Dairy'), ('condiment', 'Condiment'), ('unknown', 'Unknown')], default='veg', max_length=30)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kidtable')),
            ],
        ),
    ]
