# Generated by Django 3.2.9 on 2022-03-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetable',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
