# Generated by Django 3.2.9 on 2022-03-01 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_imagetable_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetable',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='imagetable',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
