# Generated by Django 3.2.9 on 2022-03-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220301_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetable',
            name='image_url',
            field=models.URLField(max_length=600),
        ),
    ]
