# Generated by Django 3.2.9 on 2022-03-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_imagetable_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetable',
            name='image_url',
            field=models.URLField(),
        ),
    ]
